version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-demo-wordpress
        awslogs-region: us-east-1
        awslogs-stream-prefix: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-demo-mysql
        awslogs-region: us-east-1
        awslogs-stream-prefix: mysql
